version: '3'

services:
    api:
        container_name: nestjs-api
#         tty: true
        build:
            context: ./app
            dockerfile: Dockerfile
            target: development
        env_file:
            - ./dot.env
        command: npm run start:dev
        ports:
            - 3000:3000
        volumes:
            - ./app:/usr/src/app
